[package]
name = "better_anymap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better_anymap_derive = { path = "better_anymap_derive" }
